# Welcome to Serverless!
#
# For full config options, check the kubeless plugin docs:
#    https://github.com/serverless/serverless-kubeless
#
# For documentation on kubeless itself:
#    http://kubeless.io

# Update the service name below with your own service name
service: new-project

# Please ensure the serverless-kubeless provider plugin is installed globally.
# $ npm install -g serverless-kubeless
#
# ...before installing project dependencies to register this provider.
# $ npm install

provider:
  name: kubeless
  runtime: python2.7

plugins:
  - serverless-kubeless

package:
  artifact: .serverless/new-protect.zip
  exclude:
    - venv/**
functions:
  hello:
    handler: handler.hello
    package:
      artifact: hello.zip
  clock:
    handler: handler.print_clock
    package:
      artifact: clock.zip
    events:
      - schedule: '* * * * *'
  sendmail:
      handler: handler.send_mail
      package:
        artifact: mail.zip
      events:
        - trigger: 'send_mail'
  markdown:
    handler: handler.render_markdown
    package:
      artifact: markdown.zip
